//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCTOnlineLibraryManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACCTOnlineLibraryEntities : DbContext
    {
        public ACCTOnlineLibraryEntities()
            : base("name=ACCTOnlineLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Borrow> Borrows { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyLogin> FacultyLogins { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentLogin> StudentLogins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
