//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCTOnlineLibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int BorrowID { get; set; }
        public Nullable<int> StudentLoginID { get; set; }
        public Nullable<int> FacultyLoginID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual FacultyLogin FacultyLogin { get; set; }
        public virtual StudentLogin StudentLogin { get; set; }
    }
}
