//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCTOnlineLibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public int FacultyID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public System.DateTime MemberSince { get; set; }
        public int FacultyLoginID { get; set; }
    
        public virtual FacultyLogin FacultyLogin { get; set; }
    }
}
